-- Phase 1 schema: see C:\source\specs\LinguaNest\Phase1\backend-api-spec.md (Database Schema section)
-- for the full rationale behind each table and column. Column definitions below are taken verbatim
-- from that spec; do not edit this file once applied - corrections go in a new migration.

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) UNIQUE,          -- Phase 2+: populated once real accounts exist
  password_hash VARCHAR(255),         -- Phase 2+: populated once real accounts exist
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE chats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE exercises (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chat_id UUID REFERENCES chats(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  language VARCHAR(50) NOT NULL,
  topic VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  exercise_id UUID REFERENCES exercises(id) ON DELETE CASCADE,
  question_number INT NOT NULL,
  prompt_text TEXT NOT NULL,
  answer_key TEXT NOT NULL
);

CREATE TABLE submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  exercise_id UUID REFERENCES exercises(id) ON DELETE CASCADE,
  submission_type VARCHAR(20) CHECK (submission_type IN ('TEXT', 'IMAGE')), -- IMAGE is Phase 2+
  status VARCHAR(20) CHECK (status IN ('PENDING', 'PROCESSING', 'GRADED', 'FAILED')),
  image_s3_key VARCHAR(512),          -- Phase 2+: set only for IMAGE submissions
  raw_text_input TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE graded_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id UUID REFERENCES submissions(id) ON DELETE CASCADE,
  overall_score INT,
  feedback_markdown TEXT NOT NULL,
  detailed_corrections JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_exercises_user_id ON exercises(user_id);
CREATE INDEX idx_submissions_exercise_id ON submissions(exercise_id);
